export default async function sitemap() {
    let date = new Date().toGMTString();

    const routes = [
        `/`,
        `/our-internship/`,
        `/career/`,
        `/about/`,
        `/our-services/`,
        `/page-not-found/`,
        `/terms-and-conditions/`,
        `/products/`,
        `/meet-our-team/`,
        `/contact-us/`,
        `/blogs/`,
        `/privacy-policy/`,
        `/courses/`,
        `/multistep-popup-form/`,
        `/internship/`,
        `/internship/website-designing/`,
        `/internship/web-development/`,
        `/services/`,
        `/services/logo-design/`,
        `/services/api-integration/`,
        `/services/game-development/`,
        `/services/pay-per-click/`,
        `/services/content-writing/`,
        `/services/content-marketing/`,
        `/services/social-media-marketing-agency/`,
        `/services/search-engine-optimization/`,
        `/services/digital-marketing/`,
        `/services/android-app-development-services/`,
        `/services/ios-app-development/`,
        `/services/app-development/`,
        `/services/web-designing-company/`,
        `/services/website-development/`,
        `/services/website-hosting/`,
        `/services/graphic-designing/`,
        `/blog/`,
        `/blog/reasons-your-business-needs-seo-or-search-engine-optimization/`,
        `/blog/seo-strategies-faq/`,
        `/blog/is-your-website-voice-search-friendly/`,
        `/blog/tips-to-optimize-laravel-website/`,
        `/blog/why-php-services-rule-software-market/`,
        `/blog/how-to-improve-your-websites-performance-with-codeigniter-framework/`,
        `/blog/how-digital-marketing-changing-world/`,
        `/blog/10-mind-blowing-tips-to-make-app-development-successful/`,
        `/blog/10-powerful-content-marketing-tips/`,
        `/blog/need-to-know-about-ruby-on-rails/`,
        `/blog/tips-to-improve-content-writing/`,
        `/blog/8-universal-rules-of-ui-ux-designing/`,
        `/blog/10-advanced-smm-tip/`,
        `/blog/8-advanced-ios-app-development-tips-for-beginners/`,
        `/blog/whats-so-trendy-about-game-development/`,
        `/blog/investing-in-a-professional-logo-design-reasons-explored/`,
        `/blog/artificial-intelligence-and-its-impact-on-software-testing/`,
        `/blog/native-app-vs-hybrid-app-which-platform-is-best/`,
        `/blog/will-chatbots-change-customer-experience/`,
        `/blog/an-introduction-to-mern-stack/`,
        `/blog/an-introduction-to-mean-stack/`,
        `/blog/choose-the-right-between-mean-stack-vs-mern-stack/`,
        `/blog/what-is-edge-computing-and-why-it-matters/`,
        `/blog/what-is-saas-based-applications-and-how-it-can-help-businesses/`,
        `/blog/how-to-improve-your-ppc-campaign-performance/`,
        `/blog/advanced-digital-marketing-tips/`,
        `/blog/a-brief-insight-into-natural-language-understanding/`,
        `/blog/what-is-deep-learning-and-how-does-it-work/`,
        `/blog/android-app-development-trends-for-2021/`,
        `/blog/what-is-kubernetes-everything-you-need-to-know-about-kubernetes/`,
        `/blog/what-is-docker-everything-you-need-to-know-about-docker/`,
        `/blog/front-end-web-development-tools-for-2021/`,
        `/blog/benefits-of-beacon-technology/`,
        `/blog/what-is-technical-seo/`,
        `/blog/why-you-should-not-consider-a-free-website/`,
        `/blog/why-wordpress-is-economical-yet-ideal-solution-for-small-businesses/`,
        `/blog/7-effective-tips-to-enhance-website-visibility/`,
        `/blog/why-need-mobile-responsive-website/`,
        `/blog/custom-web-development-services/`,
        `/blog/custom-api-development-services-benefits/`,
        `/blog/node-js-web-application-development/`,
        `/blog/how-to-become-a-full-stack-developer/`,
        `/blog/top-10-ideal-frameworks-for-web-development-services/`,
        `/blog/role-of-digital-marketing-services/`,
        `/blog/how-grow-with-ppc-management/`,
        `/blog/get-small-business-success-with-affordable-seo-services/`,
        `/blog/social-media-marketing-agency-for-business/`,
        `/blog/core-web-vitals-in-seo`,
    ].map((e) => ({
        url: `${process.env.NEXT_PUBLIC_WEBSITE_HOST_URL}${e}`,
        lastmod: date,
        changefreq: 'daily',
    }));

    return routes;
}
